gantt
    dateFormat  YYYY-MM-DD
    title サンプルプロジェクト

    section 設計
    要件定義 :done,    des1, 2025-09-01,2025-09-05
    設計作業 :active,  des2, 2025-09-06, 3d

    section 開発
    実装      :des3, 2025-09-09, 5d
    テスト    :des4, after des3, 3d